ngneat/elf

- docs/docs/immer.mdx
You recently changed `reduce` to `update` so this needs to change accordingly unless I'm missing something
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: Update immer.mdx

- docs/docs/repository.mdx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(repository): fix name in examples

- packages/requests/src/lib/request-data-source.spec.ts
- packages/requests/src/lib/request-data-source.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: [72](https://github.com/ngneat/elf/issues/72)
Types work correctly and match the following:
- If the user provides requestKey the returned value should be DataSource.
- If the user didn't provide requestKey the returned value should be DynamicKeyDataSource.
```
[ ] Yes
[x] No
```
> fix(requests): improve createRequestDataSource typing

- packages/entities/src/lib/active/active.ts
- packages/entities/src/lib/all.query.ts
- packages/entities/src/lib/delete.mutation.ts
- packages/entities/src/lib/entities-props-factory.spec.ts
- packages/entities/src/lib/entities-types.spec.ts
- packages/entities/src/lib/entity.utils.ts
- packages/entities/src/lib/many.query.ts
- packages/entities/src/lib/queries.ts
- packages/entities/src/lib/set.mutation.ts
- packages/entities/src/lib/union-entities.ts
- packages/pagination/src/lib/pagination.ts
- packages/requests/src/lib/request-data-source.spec.ts
- packages/requests/src/lib/requests-cache.ts
- packages/requests/src/lib/requests-status.ts
- packages/store/src/index.ts
- packages/store/src/lib/types.ts
- packages/store/src/lib/utils.ts
fix(entities): code cleanup
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[x] No
```
> fix(entities): typed support for immutable/readonly arrays

- packages/entities/src/lib/active/active.ts
- packages/entities/src/lib/all.query.ts
- packages/entities/src/lib/delete.mutation.ts
- packages/entities/src/lib/entities-props-factory.spec.ts
- packages/entities/src/lib/entities-types.spec.ts
- packages/entities/src/lib/entity.utils.ts
- packages/entities/src/lib/many.query.ts
- packages/entities/src/lib/queries.ts
- packages/entities/src/lib/set.mutation.ts
- packages/entities/src/lib/union-entities.ts
- packages/pagination/src/lib/pagination.ts
- packages/requests/src/lib/request-data-source.spec.ts
- packages/requests/src/lib/requests-cache.ts
- packages/requests/src/lib/requests-status.ts
- packages/store/src/index.ts
- packages/store/src/lib/types.ts
- packages/store/src/lib/utils.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Reverted usage of ReadonlyArray type

- packages/cli/src/commands/install.ts
```
[x] Bugfix
[ ] Feature
```
There are some links in the CLI that lead to a 404 Page Not Found.
The links have been updated.
```
[ ] Yes
[x] No
```
> fix(cli): update links (404)

- packages/entities/src/lib/all.query.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update `selectAllApply` example

- docs/docusaurus.config.js
```
[ ] Bugfix
[ ] Feature
```
Only fix url edit for documentation.
```
[ ] Yes
[x] No
```
> fix edit url docusaurus

- apps/ng/src/app/todos/state/todos.repository.ts
- apps/ng/src/app/todos/todos.component.html
- docs/docs/features/entities/entities.mdx
- packages/entities/src/index.ts
- packages/entities/src/lib/__snapshots__/entity.query.spec.ts.snap
- packages/entities/src/lib/__snapshots__/many.query.spec.ts.snap
- packages/entities/src/lib/count.query.ts
- packages/entities/src/lib/entity.query.spec.ts
- packages/entities/src/lib/entity.query.ts
- packages/entities/src/lib/entity.utils.ts
- packages/entities/src/lib/many.query.spec.ts
- packages/entities/src/lib/many.query.ts
- packages/mocks/src/index.ts
✅ Closes: discussion 111
```
[ ] Bugfix
[x] Feature
```
Issue Number: 111
```
[ ] Yes
[x] No
```
> feat(entities): add select many entities by predicate

- docs/docs/features/pagination.mdx
```
[ ] Bugfix
[ ] Feature
```
Hotfixes.
```
[ ] Yes
[x] No
```
> Docs fixes

- docs/docs/features/entities/ui-entities.mdx
- packages/entities/src/index.ts
- packages/entities/src/lib/union-entities-as-map.spec.ts
- packages/entities/src/lib/union-entities-as-map.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #130 
```
[ ] Yes
[x] No
```
> feat(entities): 🔥 add unionEntitiesAsMap operator

- docs/docs/features/persist-state.mdx
- packages/persist-state/src/index.ts
- packages/persist-state/src/lib/exclude-keys.spec.ts
- packages/persist-state/src/lib/exclude-keys.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #129
```
[ ] Yes
[x] No
```
[Discussion](https://github.com/ngneat/elf/discussions/131)
> feat(persist-state): 🔥 excludeKeys operator

- docs/docs/features/persist-state.mdx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(persist-state): 📘 improve excludeKeys() operator documentation

- packages/entities/src/lib/union-entities-as-map.spec.ts
- packages/entities/src/lib/union-entities-as-map.ts
```
[x] Bugfix
[ ] Feature
```
`unionEntitiesAsMap()` return value typing is not correct.
The return type is corrected.
```
[ ] Yes
[x] No
```
> fix(entities): 🐞 correct typing for unionEntitiesAsMap() return value

- docs/docs/features/entities/entities.mdx
- nx.json
- package-lock.json
- packages/cli/package-lock.json
- packages/entities/src/index.ts
- packages/entities/src/lib/__snapshots__/set.mutation.spec.ts.snap
- packages/entities/src/lib/set.mutation.spec.ts
- packages/entities/src/lib/set.mutation.ts
We've added a method called `setEntitiesMap` that supports key-value data structure.
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(mutation): add support for key-value structure

- packages/persist-state/src/lib/persist-state.spec.ts
- packages/persist-state/src/lib/persist-state.ts
```
[x] Bugfix
```
As of today, `persist-state` exposes a `unsubscribe` method, but it only remove the state->storage subscription. The reverse one is not unsubscribed.
I want to use `persist-state`  with a storage that will have some resource kept active, and i want to be able to free them at some point.
Issue Number: [157](https://github.com/ngneat/elf/issues/157)
When unsubscribing from persistance, both subscriptions are released.
```
[ ] Yes
[x] No
```
> fix(persist-state): unsubscribe from storage

- docs/docs/cli.mdx
- packages/cli/src/builders/active-id.builder.ts
- packages/cli/src/builders/active-ids.builder.ts
- packages/cli/src/builders/entities.builder.ts
- packages/cli/src/builders/feature-builder.ts
- packages/cli/src/builders/repo-builder.ts
- packages/cli/src/commands/repo.ts
- packages/cli/src/prompt.ts
- packages/cli/src/specs/__snapshots__/repo-builder.spec.ts.snap
- packages/cli/src/specs/repo-builder.spec.ts
- packages/cli/src/types.ts
- packages/cli/src/utils.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #162
Users can choose whether a store should be created inside a class or not.
```
[ ] Yes
[x] No
```
> feat(cli): add ability to create a store inside a class

- docs/docs/miscellaneous/hooks.mdx
- docs/sidebars.js
- packages/state-history/src/lib/state-history.ts
- packages/store/src/index.ts
- packages/store/src/lib/__snapshots__/elf-hooks.spec.ts.snap
- packages/store/src/lib/elf-hooks.spec.ts
- packages/store/src/lib/elf-hooks.ts
- packages/store/src/lib/store.spec.ts
- packages/store/src/lib/store.ts
- packages/store/src/lib/types.ts
- packages/store/src/lib/utils.spec.ts
- packages/store/src/lib/utils.ts
```
[ ] Bugfix
[x] Feature
```
N/A
Issue Number: #163 
Ability to hook into store update behavior
```
[ ] Yes
[x] No
```
I didn't update docs yet since I want to make sure that the new API is good to go.
> feat(store): 🔥 elfHooks with preStoreUpdate hook

- docs/docs/features/entities/active-ids.mdx
- packages/entities/src/lib/active/active.spec.ts
- packages/entities/src/lib/active/active.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #185
Added new get queries for active entities.
```
[ ] Yes
[x] No
```
> feat(entities): add getActiveEntity and getActiveEntities

- packages/store/src/lib/batch.ts
- [] Tests for the changes have been added (for bug fixes / features)
```
[x] Bugfix
[ ] Feature
```
Build failures due to incorrect imports
Issue Number: #196 
```
[ ] Yes
[x] No
```
> fix(store): fixes incorrect operator imports from rxjs

- packages/store/src/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(store): add proper export for enableElfProdMode

- docs/docs/features/entities/entities.mdx
- package-lock.json
- package.json
- packages/entities/src/index.ts
- packages/entities/src/lib/queries.spec.ts
- packages/entities/src/lib/queries.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> getEntitiesIds

- docs/docs/features/persist-state.mdx
Update the docs
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
[ ] Yes
[X] No
```
> docs(persist-state): add performace optimization cookbook

- docs/docs/features/requests/requests-status.mdx
```
[ ] Bugfix
[ ] Feature
```
Example for using withRequestsStatus:
`withRequestsStatus<`todos`, `todo-${string}`>()`.  
Note the comma between the keys.
---
Example for using withRequestsStatus:
`withRequestsStatus<`todos` | `todo-${string}`>()`.  
Note the pipe between the keys.
```
[ ] Yes
[x] No
```
> docs(requests-status): 📘 Fix typo

- docs/docs/third-party/sync-state.mdx
- docs/sidebars.js
```
[ ] Bugfix
[ ] Feature
```
Create a new category "Third Party" and add documentation for elf-sync-state.
```
[ ] Yes
[x] No
```
> docs(general): 📘 add elf-sync-state third party library docs

- packages/requests/src/lib/__snapshots__/requests-cache.spec.ts.snap
- packages/requests/src/lib/requests-cache.ts
- [X ] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
```
[X ] Bugfix
[ ] Feature
```
updateRequestsCache(keys, value) save invalid value
"requestsCache": {
"bar": {
"value": {"value": "partial"},
},
"foo": {
"value": {"value": "partial"},
},
},
"requestsCache": {
"bar": {
"value": "partial",
},
"foo": {
"value": …
> fix(request): fix updateRequestsCache

- docs/docs/miscellaneous/props-factory.mdx
- packages/store/src/lib/props-factory.spec.ts
- packages/store/src/lib/props-factory.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ngneat/elf/issues/274
```
[ ] Yes
[x] No
```
> feat(store): add  setPropsInitialValue to have ability update initial value passed to propsFactory

- docs/docs/troubleshooting/stale-emission.mdx
- docs/sidebars.js
Adding documentation about stale emission
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(store): add `stale-emission` docs

- package-lock.json
- package.json
- packages/cli/package-lock.json
- packages/cli/src/builders/repo-builder.ts
- packages/cli/src/utils.ts
- packages/cli/tsconfig.lib.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> small fixes

- docs/docs/third-party/sync-state.mdx
- docs/sidebars.js
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
Fix the elf-sync-state documentation.
```
[ ] Yes
[X] No
```
> Sync state docs

- package-lock.json
- package.json
```
[ ] Bugfix
[ ] Feature
[ x ] Other... Please describe: update rxjs to 7.5.5
```
```
[ ] Yes
[ ] No
```
> chore(general): update deps

- packages/entities/src/index.ts
Was so focused on getting the docs and tests right that I forgot to export the function from the main file. whoops
```
[x] Bugfix
[ ] Feature
```
> fix(entities): export moveEntity in index.ts

- packages/state-history/src/lib/entities-state-history.spec.ts
- packages/state-history/src/lib/entities-state-history.ts
```
[x] Bugfix
[ ] Feature
```
`EntitiesStateHistory` now properly works with `entityRef`
```
[ ] Yes
[x] No
```
> fix(state-history): fix `EntitiesStateHistory` to properly work with `entityRef`

- docs/docs/features/history/entities-history.mdx
- docs/docs/features/history/history.mdx
- packages/state-history/src/lib/entities-state-history.spec.ts
- packages/state-history/src/lib/entities-state-history.ts
- packages/state-history/src/lib/state-history.spec.ts
- packages/state-history/src/lib/state-history.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(state-history): expose methods for retrieving future and past

- docs/docs/features/requests/requests-status.mdx
I'm new to Elf and I've been looking for this `handleSuccess` method for way too long...
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: remove reference to handleSuccess

- docs/docs/miscellaneous/batching.mdx
- packages/store/src/lib/batch.spec.ts
- packages/store/src/lib/batch.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #361
```
[ ] Yes
[x] No
```
> feat(store): change `emitOnce` to emit only once even with all nested `emitOnce`

- docs/docs/miscellaneous/hooks.mdx
- packages/store/src/lib/__snapshots__/elf-hooks.spec.ts.snap
- packages/store/src/lib/elf-hooks.spec.ts
- packages/store/src/lib/elf-hooks.ts
- packages/store/src/lib/store.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #382 
```
[ ] Yes
[x] No
```
> feat(store):  elfHooks with preStateInit  hook

- packages/requests/src/index.ts
added resetStaleTime function to public exports
```
[x] Bugfix
[ ] Feature
```
I forgot to add the resetStaleTime function to the public exports.
> fix(requests-result): add resetStaleTime to export

- docs/docs/cli.mdx
Improvement of documentation
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
Typo in documentation
Typo fixed :) 
```
[ ] Yes
[X] No
```
> Fix typo in documentation

- packages/store/src/lib/store.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #461
Using `store.combine()` should spread it's emitted value thus avoiding mutations.
```
[x] Yes
[ ] No
```
> fix(store): combine should emit a new object

- docs/docs/features/entities-management/entities.mdx
- packages/entities/src/index.ts
- packages/entities/src/lib/queries.spec.ts
- packages/entities/src/lib/queries.ts
```
[ ] Bugfix
[x] Feature
```
Added a function for find entity by predicate function
```
[ ] Yes
[x] No
```
> feat(entities): added a function getEntityByPredicate

- docs/docs/features/entities-management/entities.mdx
```
[ ] Bugfix
[ ] Feature
```
Fixed mistake on documentation
```
[ ] Yes
[x] No
```
> fix(doc): fixed mistake on documentation

- docs/docs/miscellaneous/operators.mdx
Fixed typo in `distinctUntilChanged` function name.
```
[ ] Bugfix
[ ] Feature
```
`distinctUntillChanged`
`distinctUntilChanged`
```
[ ] Yes
[x] No
```
> docs: misc/operators typo on distinctUntilChanged

- docs/docs/miscellaneous/batching.mdx
- packages/store/src/index.ts
- packages/store/src/lib/batch.spec.ts
- packages/store/src/lib/batch.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #478 
```
[ ] Yes
[x] No
```
> feat(store): async batch operations

- docs/docs/dev-tools.mdx
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> doc: fix ngeat/effects typo
