- docs/docs/examples/entities-props.ex.ts
- docs/docs/features/entities/entities-props-factory.mdx
- docs/docs/features/entities/entities.mdx
- packages/entities/src/index.ts
- packages/entities/src/lib/__snapshots__/update.mutation.spec.ts.snap
- packages/entities/src/lib/update.mutation.spec.ts
- packages/entities/src/lib/update.mutation.ts
I took a stab at implementing the upsertEntities mutator, I hope you don't mind.
I haven't done the docs yet, because I wanted to get feedback before doing that.
What do you think, will this be a good implementation?
// Leon
```
[ ] Bugfix
[x] Feature
[x] Refactoring (no functional changes, no api changes)
```
We haven't got an upsertEntities mutator, only an addEntities, and a upsertEntities (byId)
I renamed upsertEntities to upsertEntitiesById
https://github.com/ngneat/elf/discussions/75
```ts
// single …
```
> feat(entities): upsertEntities mutator

- packages/state-history/src/lib/state-history.spec.ts
- packages/state-history/src/lib/state-history.ts
When stateHistory is paused, the previous value is partially retained when updating.
```
[x] Bugfix
[ ] Feature
```
[Issue Number: 91](https://github.com/ngneat/elf/issues/91)
```
[ ] Yes
[x] No
```
> fix(state-history): undo history glitch

- packages/entities/src/lib/active/active.spec.ts
- packages/entities/src/lib/active/active.ts
_I am not sure if there should be a documentation update to accompany this._
```
[x] Bugfix
[ ] Feature
```
The `selectActiveEntity` operator is typed such that the resulting observable appears to only ever emit an entity.
The typing now reflects that the resulting observable can also emit undefined if there is no active entity or if the active ID doesn't match an entity in the store.
```
[x] Yes
[ ] No
```
There is no breaking actual behavior change, …
> fix(entities): correct typing for selectActiveEntity

- docs/docs/features/entities/entities.mdx
- packages/entities/src/lib/__snapshots__/update.mutation.spec.ts.snap
- packages/entities/src/lib/update.mutation.spec.ts
- packages/entities/src/lib/update.mutation.ts
```
[ ] Bugfix
[x] Feature
```
id update via `updateEntities` is not supported
Issue Number: #146 
id update via `updateEntities` is supported
```
[ ] Yes
[x] No
```
The `updateStateIds` function could have been less verbose - I could have used a simple `map`. However, I wanted to optimize the loop and break out from it as soon as ids are updated.
There was no need to update `upsertEntities` since its syntax does not support updating ids. The `upsertEntitiesById` …
> feat(entities): 🔥 support id update

- docs/docs/features/requests/requests-cache.mdx
```
[ ] Bugfix
[ ] Feature
```
according to docs, `withRequestsCache` accepts two parameters like `withRequestsCache<'todos','todo-${string}'>()`, while the API accepts only one parameter.
This PR updates the docs to sync with API.
```
[ ] Yes
[x] No
```
> docs: fixes incorrect number of parameters in `withRequestsCache`

- docs/docs/features/requests/requests-status.mdx
- docs/docs/repository.mdx
```
[ ] Bugfix
[ ] Feature
```
Documentation for the repository pattern has the current behavior:
1.  Functional example calls `createStore` with `{name}` with no name set.  
2. OOP acronym is not defined.  Learner bias that everyone knows that OOP is Object-oriented programming.  Most do, but such little effort to serve all.  ❤️ 
3. OOP example is not complete:  Instead, you get `// ...`.  Approach bias.  Functional fans get a complete example.  OOP fans do not. …
> docs(general): provide oop example that matches cli output and fix functional example

- packages/persist-state/src/index.ts
- packages/persist-state/src/lib/storage.ts
```
[x] Bugfix
[ ] Feature
```
MaybeAsync type is not exported from @ngneat/elf-persist-state
MaybeAsync is exported from @ngneat/elf-persist-state
```
[ ] Yes
[x] No
```
It might be useful for a custom StateStorage, since it's required to return this type in the implementation
> fix(persist-state): added missing export "MaybeAsync" type

- CONTRIBUTING.md
```
[ ] Bugfix
[ ] Feature
```
Angular repo switched from `master` to `main` and the link became broken
The link to commit message examples is working
```
[ ] Yes
[x] No
```
Also the MD formatter (probably Prettier) added a new line after H2 which is more compliant with the standard, I guess. I think there is no harm to keep it to prevent it from being added again at least.
> docs(contributing): fix broken link

- docs/docs/dev-tools.mdx
- [ x] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
The docs lack information on how to include a custom actions stream into the devtools.
The docs contain a section which will describe how to include a sample actions …
> docs(dev-tools): Add guide to show ngneat/effects in dev-tools

- packages/state-history/src/lib/state-history.ts
```
[x] Bugfix
[ ] Feature
```
There is an error 
```ts
export class Repo {
readonly stateHistory = stateHistory(store);
}
TS4029: Public property 'stateHistory' of exported class has or is using name 'StateHistory' from external module "/node_modules/@ngneat/elf-state-history/lib/state-history" but cannot be named.
```
Class `StateHistor` is exported so `stateHistory` can be properly used
```
[ ] Yes
[x] No
```
> fix(state-history): export StateHistory to be able to use stateHistory

- docs/docs/examples/entities-state-history.ex.ts
- packages/state-history/src/lib/entities-state-history.spec.ts
- packages/state-history/src/lib/entities-state-history.ts
…h initial entities
```
[x] Bugfix
[ ] Feature
```
`EntitiesStateHistory` didn't consider entities set as an initial value
```
[ ] Yes
[x] No
```
> fix(state-history): fix `EntitiesStateHistory` to make it consider initial entities

- docs/docs/features/entities/entities.mdx
- packages/entities/src/lib/__snapshots__/move.mutation.spec.ts.snap
- packages/entities/src/lib/move.mutation.spec.ts
- packages/entities/src/lib/move.mutation.ts
in Akita there is a move function on the entities store that moves an id in the ids array to a new position.
This mutator is a copy of the functionality from that function.
```
[ ] Bugfix
[x] Feature
```
> feat(entities): moveEntity

- packages/persist-state/src/lib/storage.ts
getting localStorage or sessionStorage in an environment where they throw an error, will cause elf to fail.
```
[x] Bugfix
[ ] Feature
```
We don't wrap the access to window.localStorage causing problems.
https://github.com/ngneat/elf/issues/323
We wrap the access so that it wont fail in chrome incognito mode.
```
[ ] Yes
[x] No
```
> fix(persist-state): wrap storage in try catch

- docs/docs/features/pagination.mdx
As I was using elf state management in my project I referenced the docs, and because of line 55 in pagination.mdx I assumed that elf pagination started at index 1. This cause a lot of extra work for myself, I did not even try to check if there was a page "0". I just wanted to propose some sort of clarification to the docs so that first time users of elf are aware that they can start their pagination at index 0.
```
[ ] Bugfix
[ ] Feature
```
Just some …
> docs: add clarification to pagination.mdx

- packages/pagination/src/lib/pagination.ts
(only single 'export' statement, no functional changes)
(only single 'export' statement, no functional changes)
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
Attempting to export a function which has a return type that contains a store with pagination leads to a typescript error:
- `Return type of exported function has or is using name 'PaginationState' from external module "node_modules/@ngneat/elf-pagination/lib/pagination" but cannot be named.ts(4058)`
See discussion #377 
- …
> feat(pagination): exported pagination state

- docs/docs/features/requests-result.mdx
- packages/requests/src/lib/requests-result.spec.ts
- packages/requests/src/lib/requests-result.ts
Introduce skipWhileFetching to options for trackRequestResult function. This allows to skip duplicated parallel requests.
#403
```
[ ] Bugfix
[x] Feature
```
It is possible to trigger the same request multiple times until the first request is successful
Issue Number: #403
Introduce skipWhileLoading to options for trackRequestResult function. This allows to skip duplicated parallel requests.
```
[ ] Yes
[x] No
```
> feat(requests): support skipping duplicated parellel requests

- packages/store/package.json
```
[x] Bugfix
[ ] Feature
```
Currently this package causes typescript to be a production dependency.
Now typescript wont be considered a production dependency which can be ignored when running `npm ci --omit=dev`. Also I added rxjs as a peer dependency as it is actually needed by the store.
```
[ ] Yes
[x] No
```
> fix: store peer dependencies

- packages/entities/src/lib/__snapshots__/update.mutation.spec.ts.snap
- packages/entities/src/lib/update.mutation.spec.ts
- packages/entities/src/lib/update.mutation.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ngneat/elf/issues/437
```
[ ] Yes
[x] No
```
> fix(entities): make updateEntities skip updating by entities ids that do not present in the store

- docs/docs/features/requests-result.mdx
- packages/requests/src/lib/requests-result.spec.ts
- packages/requests/src/lib/requests-result.ts
Introduce cacheResponseData to options for trackRequestResult function. This allows to cache the response data and return it in consecutive calls of the cached request
#443
- [/] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [/] Tests for the changes have been added (for bug fixes / features)
- [/] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
For skipped requests …
> feat(requests): support caching response data in request result (#443)

- docs/docs/dev-tools.mdx
- packages/devtools/src/lib/devtools.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #296
Add log trace option to dev tools
```
[ ] Yes
[x] No
```
> feat(devtools): add option for log trace

- packages/requests/src/index.ts
```
[x] Bugfix
[ ] Feature
```
At this moment, the requests package doesn't expose the [RequestResult](https://github.com/ngneat/elf/blob/master/packages/requests/src/lib/requests-result.ts#L59) type even though it is mentioned in the [docs](https://ngneat.github.io/elf/docs/features/requests-result/#api).
Similarly to [Request Status](https://ngneat.github.io/elf/docs/features/requests/requests-status/) (see [StatusState](https://github.com/ngneat/elf/blob/master/packa …
> fix(requests): expose RequestResult

- docs/docs/features/history/history.mdx
- packages/state-history/src/lib/state-history.spec.ts
- packages/state-history/src/lib/state-history.ts
An option called resetFutureOnNewState has been added to the StateHistoryOptions interface. This option allows the user to control whether the future redo states should be cleared when a new state is added after the user has undone one or more state changes. The default value of this option is set to false, meaning that by default, the future states will not be cleared.
```
[ ] Bugfix
[x] Feature
```
Currently, when a new state is added after the user has undone one or …
> feat(state-history): 🔥 Add an option to control future state

- docs/docusaurus.config.js
This update includes OpenGraph and Twitter attributes in the HTML header. This enhances sharing experiences on social media. Shared content now presents more rich and relevant information.
```
[ ] Bugfix
[ ] Feature
```
[As can be seen here](https://www.opengraph.xyz/url/https%3A%2F%2Fngneat.github.io%2Felf%2F), sharing Elf's url does not look good -
When this changes are deployed, sharing Elf would look like this -
```
[ ] Yes
[ X] No
```
> feat: add OpenGraph and Twitter attributes to header

- docs/docs/features/requests/requests-cache.mdx
- packages/requests/src/lib/requests-cache.spec.ts
- packages/requests/src/lib/requests-cache.ts
Add a ttl parameter to the updateRequestsCache function, allowing users to set an expiration time for each cache record when updating multiple keys. If a ttl value isn't provided, the cache record doesn't expire.
✅ Closes: 471
```
[ ] Bugfix
[x] Feature
```
Currently, the updateRequestsCache function updates the cache state for a given set of keys to a specified value. However, it doesn't allow for setting an expiration time for these cache records. 
Issue Number: 471 …
> feat(requests-result): 🔥 Add ttl to updateRequestsCache

- packages/requests/src/lib/requests-result.ts
```
[x] Bugfix
```
When using resetStaleTime staleTime becomes undefined and then the check fails, because it compares undefined < Date.now()
We use 0 instead of undefined for staleTime, that it doesn't fail with undefined
```
[ ] Yes
[x] No
```
We could also change resetStaleTime to reset the staleTime to 0 instead of undefined.
> fix(requests): staleTime can be undefined

- README.md
[x] Docs have been added
I've been a dedicated user of the Elf family of packages, and I'm continuously impressed by the quality and usefulness of these libraries. I wanted to suggest an enhancement that could further improve the user experience for everyone who uses these packages.
I've noticed that the README for the Elf family packages doesn't currently include a link to an NPM usage trend tool. Adding such a link would allow users to easily access important metrics such as usage trends, the latest commit time, and GitHub star counts for each of the Elf family packages.
I believe that providing easy access to these metrics will be beneficial for both new users exploring these packages and existing users who want to stay updated with their popularity. …
> Add NPM Usage Trend Link to README

- packages/requests/src/lib/requests-result.spec.ts
- packages/requests/src/lib/requests-result.ts
This fixes #485 
trackRequestResult no longer considers staleTime when skipping a request with status: fetching.
```
[x] Bugfix
[ ] Feature
```
It's currently possible to have concurrent requests even if preventConcurrentRequest is true because all requests that are 'fetching' are also stale.
Issue Number: #485 
The stale time is not considered at all when deciding wether to skip a request or not for fetching requests.
An alternative solution would be to set the stale …
> fix(requests): preventConcurrentRequest along with staleTime

- docs/docs/cli.mdx
- packages/cli/src/builders/active-id.builder.ts
- packages/cli/src/builders/active-ids.builder.ts
- packages/cli/src/builders/entities.builder.ts
- packages/cli/src/builders/feature-builder.ts
- packages/cli/src/builders/repo-builder.ts
- packages/cli/src/specs/__snapshots__/repo-builder.spec.ts.snap
- packages/cli/src/specs/repo-builder.spec.ts
- packages/cli/src/types.ts
- packages/cli/src/utils.ts
Allow build repo class without constructor
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ngneat/elf/issues/492
```
[ ] Yes
[x] No
```
> feat(cli): allow build repo class without constructor

- docs/docs/features/persist-state.mdx
- packages/mocks/src/index.ts
- packages/persist-state/src/lib/persist-state.spec.ts
- packages/persist-state/src/lib/persist-state.ts
The `preStorageUpdate` feature in the `persistState` function allows you to modify the state of your application before it is saved to storage. This is particularly useful when you want to remove or transform certain parts of the state before persisting it. For example, you might want to remove sensitive data or unnecessary information. The function receives the store's name and the current state as parameters and should return the modified state which will then be saved to storage.
✅ Closes: [490](https://github.com/ngneat/elf/issues/490)
```
[ ] Bugfix
[x] Feature
[ ] Build …
```
> feat(persist-state): 🔥 Add callback to change state before save

- docs/docs/side-effects.mdx
```
[ ] Bugfix
[ ] Feature
```
`createAction` import is missing in the docs of `side-effects`
`createAction` import is added in the docs of `side-effects`
```
[ ] Yes
[x] No
```
> fix(doc): import `createAction` in side-effects.mdx

- docs/docs/features/requests/requests-cache.mdx
- packages/requests/src/index.ts
- packages/requests/src/lib/requests-cache.spec.ts
- packages/requests/src/lib/requests-cache.ts
New function 'deleteRequestsCache'
resolves #515
```
[ ] Bugfix
[x] Feature
```
@ngneat/elf-requests does not support removing a single request cache by key
Issue Number: #515 
New function 'deleteRequestsCache' can invalidate in cache a single key or list of keys
```
[ ] Yes
[x] No
```
> feat: add support for removing a single request cache by key(#515)

- packages/entities/src/lib/update.mutation.spec.ts
- packages/entities/src/lib/update.mutation.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #518 
For duplicate entities, the latter one will be merged into the former one. The resulting `ids` array will not have duplicate ids.
```
[ ] Yes
[x] No
```
> fix(entities): correct behavior of `upsertEntities` with duplicate entities
